### ISSUE TITLE
appveyor

### ISSUE THREAD

**Issue by 9renpoto** [9renpoto/js#52]
- flow type は windows で動かないので `src`, `test` を babel でビルドして `.tmp` などのところに追加
- ビルド後のものだけテストを実行するように appveyor.yml を修正

**Comment by taka-sho** [comment]
はい

**Comment by 9renpoto** [comment]
eslint もしなくて良い

`nyc mocha -- .tmp/test` などが動けば良い

**Comment by 9renpoto** [comment]
もちろん eslint は travis ないし別のCI上で動いているから、という前提

**Comment by taka-sho** [comment]
すいません。[こちら](https://ci.appveyor.com/project/9renpoto/js/build/1.0.31#L1126)のエラーが予測がつかないのですがどのようになっているのでしょうか

**Comment by taka-sho** [comment]
2回トランスパイラを通そうとしているからエラーが出てくる、という予測をしています
